### ISSUE TITLE
Heart Icons in the Journal Poem don't get reskinned

### ISSUE THREAD

**Issue by XavierShrier** [l-Luna/AltSidesHelper#6]
Self explanatory, while custom textures do get applied to both the file select and general progress in the journal, the icons under the poem page don't change.

**Comment by l-Luna** [comment]
note to self: use two IL hooks, one when the poem lines are constructed to associate them with their IDs, and one during line rendering to actually display the right sprite.

**Comment by l-Luna** [comment]
now implemented!
